include: package:flutter_lints/flutter.yaml

# Configurações personalizadas de linting para o projeto
linter:
  rules:
    avoid_print: false # evita prints
    avoid_redundant_argument_values: false # avisa se o valor passado no argumento é igual seu valor padrão
    avoid_unnecessary_containers: true # evita containers desnecessários
    unnecessary_this: true # evita 'this.' desnecessários
    unnecessary_late: true # evita 'late' desnecessário
    unnecessary_new: true # evita 'new' (desnecessário no Dart moderno)
    prefer_final_locals: true # variáveis locais 'final' quando possível
    always_put_required_named_parameters_first: true # parâmetros nomeados obrigatórios primeiro
    curly_braces_in_flow_control_structures: true # exibe '{}' el if/else/for
    avoid_types_as_parameter_names: true # evita nomear parâmetros com nomes de tipos
    avoid_unused_constructor_parameters: true # evita parâmetros de construtor não utilizados
    sized_box_for_whitespace: true # recomenda usar SizedBox para espaçamento
    use_full_hex_values_for_flutter_colors: true # obriga usar formato completo da cor (com alpha)
    use_key_in_widget_constructors: true # recomenda usar 'key' em construtores de widgets
    avoid_positional_boolean_parameters: true # evita parâmetros booleanos posicionais (recomendado usar nomeados)
    prefer_single_quotes: true # recomenda aspas simples

    # Recomendar 'const' sempre que possível
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true # evita 'const' desnecessários


#
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
