import type { Metadata } from "next"
import { Figtree } from "next/font/google" // fonte
import "./globals.css"

/**
 * Fonte padrão do app: Figtree.
 */
const figtree = Figtree({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

/**
 * Metadados gerais da aplicação.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

/**
 * Layout raiz da aplicação.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${figtree.className} antialiased h-dvh`}>{children}</body>
    </html>
  )
}
